Repository micronaut-projects/micronaut-kotlin, pull requests merged in 2020-07, with the labels that each got.

#96 [kotlin] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#97 [kotlin] Update common files for branch master
  .github/workflows/dependency-check.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#99 [kotlin] Update common files for branch master
  .github/dependabot.yml
Labels: relates-to: build

#101 [kotlin] Update common files for branch master
  .github/settings.yml
  .github/workflows/label-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#102 Dependency upgrades
  kotlin-extension-functions/build.gradle
Labels: type: dependency-upgrade

#114 Remove Probot settings file
  .github/settings.yml
Labels: relates-to: build

#115 Dependency upgrades
  kotlin-extension-functions/build.gradle
  kotlin-runtime/build.gradle
  ktor/build.gradle
Labels: type: dependency-upgrade

#113 Fix loading of HOCON external properties via "micronaut.config.files"
  kotlin-runtime/src/main/kotlin/io/micronaut/context/env/hocon/HoconPropertySourceLoader.kt
  kotlin-runtime/src/test/kotlin/io/micronaut/context/env/hocon/HoconPropertySourceLoaderTest.kt
  kotlin-runtime/src/test/resources/config_file.conf
Labels: type: bug
