Repository micronaut-projects/micronaut-kotlin, pull requests merged in 2023-05, with the labels that each got.

#499 Allow running ktor servers as applications
  examples/greeting/build.gradle
  ktor/src/main/kotlin/io/micronaut/ktor/server/AbstractKtorEmbeddedServer.kt
  settings.gradle
Labels: type: bug

#502 [kotlin] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
  examples/greeting/build.gradle
Labels: relates-to: build

#503 ci: Github release workflow sync
  .github/workflows/release.yml
Labels: relates-to: build

#506 Kotlin to M5
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.kotlin-base.gradle
  examples/greeting/build.gradle
  gradle.properties
  gradle/libs.versions.toml
  kotlin-extension-functions/build.gradle
  kotlin-runtime/build.gradle
  ktor/build.gradle
  settings.gradle
Labels: type: dependency-upgrade

#508 Fix documentation task
  buildSrc/src/main/groovy/io.micronaut.build.internal.kotlin-module.gradle
  kotlin-runtime/build.gradle
Labels: type: docs, relates-to: build

#510 [kotlin] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
